set_property MARK_DEBUG true [get_nets {VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/gat_state[0]}]
set_property MARK_DEBUG true [get_nets {VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/word_pointer_reg[5]__0_0[0]}]
set_property MARK_DEBUG true [get_nets {VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/word_pointer_reg[5]__0_0[1]}]
set_property MARK_DEBUG true [get_nets VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/gat_enable]
set_property MARK_DEBUG true [get_nets VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/gat_ready]
set_property MARK_DEBUG true [get_nets VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/gat_state0]
set_property MARK_DEBUG true [get_nets VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/output_buff]
set_property MARK_DEBUG true [get_nets VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/vga_h_display]
set_property MARK_DEBUG true [get_nets VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/vga_h_v_display]
set_property MARK_DEBUG true [get_nets VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/vga_state0__0]
set_property MARK_DEBUG true [get_nets {VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/vga_state[0]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/vga_state[1]_i_1_n_0}]
set_property MARK_DEBUG true [get_nets {VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/vga_state[1]_i_2_n_0}]
set_property MARK_DEBUG true [get_nets {VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/vga_state_reg_n_0_[0]}]
set_property MARK_DEBUG true [get_nets {VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/vga_state_reg_n_0_[1]}]
set_property MARK_DEBUG true [get_nets VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/vga_synch]
set_property MARK_DEBUG true [get_nets VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/wea]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list VGA_top_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/gat_state[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 2 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/word_pointer_reg[5]__0_0[0]} {VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/word_pointer_reg[5]__0_0[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/gat_enable]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/gat_ready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/gat_state0]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/output_buff]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/vga_h_display]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/vga_h_v_display]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/vga_state0__0]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/vga_state[0]_i_1_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/vga_state[1]_i_1_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/vga_state[1]_i_2_n_0}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/vga_state_reg_n_0_[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/vga_state_reg_n_0_[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/vga_synch]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list VGA_top_i/VGA_v1_0_0/U0/VGA_controller_0/wea]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
