# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Zynq_Book/VGA_1_0_D/VGA_1_0_D.srcs/sources_1/ip/blk_mem_gen_pixel/blk_mem_gen_pixel.xci
# IP: The module: 'blk_mem_gen_pixel' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Zynq_Book/VGA_1_0_D/VGA_1_0_D.srcs/sources_1/ip/blk_mem_gen_pixel/blk_mem_gen_pixel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_pixel'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Zynq_Book/VGA_1_0_D/VGA_1_0_D.srcs/sources_1/ip/blk_mem_gen_pixel/blk_mem_gen_pixel.xci
# IP: The module: 'blk_mem_gen_pixel' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Zynq_Book/VGA_1_0_D/VGA_1_0_D.srcs/sources_1/ip/blk_mem_gen_pixel/blk_mem_gen_pixel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_pixel'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
