# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Zynq_Book/VGA_mem_mapped/zedboard_constraints.xdc

# XDC: new/debug.xdc

# Block Designs: bd/VGA_top/VGA_top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_top || ORIG_REF_NAME==VGA_top} -quiet] -quiet

# IP: bd/VGA_top/ip/VGA_top_processing_system7_0_0/VGA_top_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_top_processing_system7_0_0 || ORIG_REF_NAME==VGA_top_processing_system7_0_0} -quiet] -quiet

# IP: bd/VGA_top/ip/VGA_top_axi_interconnect_0_0/VGA_top_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_top_axi_interconnect_0_0 || ORIG_REF_NAME==VGA_top_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/VGA_top/ip/VGA_top_axi_interconnect_1_0/VGA_top_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_top_axi_interconnect_1_0 || ORIG_REF_NAME==VGA_top_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/VGA_top/ip/VGA_top_rst_ps7_0_100M_0/VGA_top_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_top_rst_ps7_0_100M_0 || ORIG_REF_NAME==VGA_top_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/VGA_top/ip/VGA_top_VGA_v1_0_0_0/VGA_top_VGA_v1_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_top_VGA_v1_0_0_0 || ORIG_REF_NAME==VGA_top_VGA_v1_0_0_0} -quiet] -quiet

# IP: bd/VGA_top/ip/VGA_top_axi_gpio_0_0/VGA_top_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_top_axi_gpio_0_0 || ORIG_REF_NAME==VGA_top_axi_gpio_0_0} -quiet] -quiet

# IP: bd/VGA_top/ip/VGA_top_xbar_0/VGA_top_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_top_xbar_0 || ORIG_REF_NAME==VGA_top_xbar_0} -quiet] -quiet

# IP: bd/VGA_top/ip/VGA_top_auto_pc_1/VGA_top_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_top_auto_pc_1 || ORIG_REF_NAME==VGA_top_auto_pc_1} -quiet] -quiet

# IP: bd/VGA_top/ip/VGA_top_auto_pc_0/VGA_top_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VGA_top_auto_pc_0 || ORIG_REF_NAME==VGA_top_auto_pc_0} -quiet] -quiet

# XDC: bd/VGA_top/VGA_top_ooc.xdc
