# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Zynq_Book/VGA_mem_mapped/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_xbar_0/VGA_top_xbar_0.xci
# IP: The module: 'VGA_top_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Zynq_Book/VGA_mem_mapped/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_xbar_0/VGA_top_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_top_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Zynq_Book/VGA_mem_mapped/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_xbar_0/VGA_top_xbar_0.xci
# IP: The module: 'VGA_top_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Zynq_Book/VGA_mem_mapped/VGA_mem_mapped.srcs/sources_1/bd/VGA_top/ip/VGA_top_xbar_0/VGA_top_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGA_top_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
